spring:
  main:
    banner-mode: off
  application:
    name: "cellphones-fake"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce
    username: admin
    password: admin
server:
  port: 8082
logging:
  level:
    org:
      hibernate:
        SQL: trace

role_user: USER
role_admin: ADMIN
token_secret_key: 716B14F1B162E3CC4674CCE4FAD94E3EA2E4E4583FEB6CBAAE8861B352