spring:
  application:
    name: "cellphones-fake"
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/ecommerce
    username: admin
    password: admin
server:
  port: 8082
logging:
  level:
    org:
      hibernate:
        SQL: trace

role_user: ROLE_USER
role_admin: ROLE_ADMIN